

INSERT INTO  user_account(id, country, e_mail, is_filled, is_verified, username, nick, password,authorities)
VALUES (1,'Polska' ,'Truskawki@gmail.com',true,true,'walecznyrycerz99',	'Pogromca smaku','$2a$06$86wYILRRu.fGIrXn9uuxG.CQHLPtfzjsssd9jMY62eM6FKcvFniOm','ROLE_USER'),
(2,	'Polska','borkowski95@onet.pl',	true,true,'noth168','Braines','$2a$06$86wYILRRu.fGIrXn9uuxG.CQHLPtfzjsssd9jMY62eM6FKcvFniOm','ROLE_USER'),
( 3,'Polska','jechaneztymkoksem@wp.pl',true,true,'Terqa5','Terka99'	,'$2a$06$86wYILRRu.fGIrXn9uuxG.CQHLPtfzjsssd9jMY62eM6FKcvFniOm', 'ROLE_USER'),
(4,'Polska', 'emailpo@gmail.com',true, true, 'admin','admin','$2a$06$Vsgf.quMHsFTOWJXayJV1umaJMcs1FUFrs9uwc1QFBJRh9RHkPQNC','ROLE_ADMIN');


INSERT INTO cuisines(name)
VALUES
('kuchniaargentyńska'),
('kuchniabrazylijska'),
('kuchniaamerykańska (USA)'),
('kuchniaalaskańska'),
('kuchniaamerykańsko-chińska'),
('kuchniaamerykańsko-indyjska'),
('kuchniahawajska'),
('kuchniaindiańska (zróżnicowana)'),
('kuchniakalifornijska'),
('kuchnialuizjańska (cajun)'),
('kuchniamurzyńska'),
('kuchniaportorykańska'),
('kuchniateksańska'),
('kuchniawhite trash'),
('kuchniakanadyjska'),
('kuchniakubańska'),
('kuchniameksykańska'),
('kuchniaaustralijska'),
('kuchniaarabska'),
('kuchniachińska'),
('kuchniaindonezyjska'),
('kuchniaindyjska'),
('kuchniajapońska'),
('kuchniatajska'),
('kuchniaturecka'),
('kuchniauzbecka'),
('kuchniawietnamska'),
('kuchniaaustriacka'),
('kuchniabaskijska'),
('kuchniabiałoruska'),
('kuchniabrytyjska'),
('kuchniaangielska'),
('kuchniaszkocka'),
('kuchniawalijska'),
('kuchniabułgarska'),
('kuchniachorwacka'),
('kuchniaczeska'),
('kuchniaestońska'),
('kuchniafińska'),
('kuchniafrancuska'),
('kuchniagrecka'),
('kuchniahiszpańska'),
('kuchniaholenderska'),
('kuchniairlandzka'),
('kuchniakatalońska'),
('kuchnialitewska'),
('kuchniamaltańska'),
('kuchnianiemiecka'),
('kuchniapolska'),
('kuchniaportugalska'),
('kuchniarosyjska'),
('kuchniarumuńska'),
('kuchniasłoweńska'),
('kuchniaśląska'),
('kuchniaukraińska'),
('kuchniawęgierska'),
('kuchniawłoska');

INSERT INTO user_details(id, birth_date, city, description, flat_number, interests, name, phone_number, photo, post_code, profile_completion, sex, street, street_number, surname,preferred_cuisine_id, user_account_id)
VALUES
(2,	'1995-05-17','Krasnystaw',null,20,'Informatyka','Łukasz',725150126,	null,'22-300',8,'m','Piekarskiego',	20,	'Borkowski',10,2),
(1,	'1992-12-12','Lublin',null,12,'Rolnictwo','Izabela',12313123,null,'44-555',	8,'k','Rzecka',	23,	'Łęcka',19,1),
(3,	'1985-11-11','Opole',null,44,'Kolarstws o, Filmy','Tomasz',997997997,null,'99-777',8,'m','Chujowa',100,'Terka',3,3),
(4,	'1985-11-11','Opole',null,44,'Kolarstws o, Filmy','Tomasz',997997997,null,'99-777',8,'m','Chujowa',100,'Terka',3,3)
